### ISSUE TITLE
i get this error when i try to run it 

### ISSUE THREAD

**Issue by Raroll** [NozzOne/topgg-voter#4]
Unhandled error processing page session : Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\flet\flet.py", line 302, in on_session_created
    session_handler(page)
  File "C:\Users\topgg-voter-main\src\main.py", line 129, in main
    check_vote(tray, None) # check_vote
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\topgg-voter-main\src\main.py", line 30, in check_vote
    voter.start(e=None)
  File "C:\Users\topgg-voter-main\src\app.py", line 54, in start
    driver = Chrome(True, Browser.CHROME,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\topgg-voter-main\src\chrome.py", line 26, in __init__
    self.driver = uc.Chrome(options=self._options(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 456, in __init__
    service = selenium.webdriver.common.service.Service(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class Service with abstract method command_line_args

**Comment by valentin-marquez** [comment]
This is due to a bug in undetected chromedriver reported [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/967)

You can fix it by following this post [HERE](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/623#issuecomment-1119702638) or you can uninstall the current version of undetected-chromedriver and install the [fork]( https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/623#issuecomment-1235323799) which sebdelsol did to fix it

Finally I want to say that I plan to patch it for the next version of the program.
